In [1]:
!pip uninstall numpy -y

Found existing installation: numpy 1.26.4
Uninstalling numpy-1.26.4:
  Successfully uninstalled numpy-1.26.4


In [2]:
!pip install numpy==1.26.4

  Using cached numpy-1.26.4-cp310-cp310-win_amd64.whl.metadata (61 kB)
Using cached numpy-1.26.4-cp310-cp310-win_amd64.whl (15.8 MB)


ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
mediapipe 0.10.14 requires protobuf<5,>=4.25.3, but you have protobuf 3.19.4 which is incompatible.


In [3]:
!pip install -U scikit-learn

  Using cached joblib-1.4.2-py3-none-any.whl.metadata (5.4 kB)
  Using cached threadpoolctl-3.5.0-py3-none-any.whl.metadata (13 kB)
   ---------------------------------------- 0.0/11.0 MB ? eta -:--:--
   ---------------------------------------- 0.1/11.0 MB 1.7 MB/s eta 0:00:07
   - -------------------------------------- 0.5/11.0 MB 6.3 MB/s eta 0:00:02
   ---- ----------------------------------- 1.3/11.0 MB 10.4 MB/s eta 0:00:01
   --------- ------------------------------ 2.5/11.0 MB 14.6 MB/s eta 0:00:01
   --------------- ------------------------ 4.3/11.0 MB 19.6 MB/s eta 0:00:01
   -------------------------- ------------- 7.2/11.0 MB 27.0 MB/s eta 0:00:01
   ---------------------------------------  11.0/11.0 MB 46.9 MB/s eta 0:00:01
   ---------------------------------------- 11.0/11.0 MB 43.7 MB/s eta 0:00:00
Using cached joblib-1.4.2-py3-none-any.whl (301 kB)
Using cached threadpoolctl-3.5.0-py3-none-any.whl (18 kB)


In [4]:
import numpy as np
import glob
import os
from tensorflow.keras.utils import to_categorical
from sklearn.model_selection import train_test_split
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Flatten, Dropout
from tensorflow.keras.callbacks import ModelCheckpoint, EarlyStopping

In [5]:
os.environ["CUDA_VISIBLE_DEVICES"] = "0"

In [90]:
gesture = {
    0:'A', 1:"B", 2:"C", 3:'D', 4:'E', 5:'F', 6:'G', 7:'H', 8:'I', 9:'J', 10:'K', 11:'L', 12:'M', 13:'N', 14:'O', 15:'P',
    16:'Q', 17:'R', 18:'S', 19:'T', 20:'U', 21:'V', 22:'W', 23:'X', 24:'Y', 25:'Z',
}

In [91]:
len(gesture)

26

In [92]:
path = "C://ai_project01/hand_detect01/hand_dataset/*.npy"

In [93]:
file_list = glob.glob(path)

file_list

['C://ai_project01/hand_detect01/hand_dataset\\A_1721720557.npy',
 'C://ai_project01/hand_detect01/hand_dataset\\B_1721721796.npy',
 'C://ai_project01/hand_detect01/hand_dataset\\C_1721721850.npy',
 'C://ai_project01/hand_detect01/hand_dataset\\D_1721881189.npy',
 'C://ai_project01/hand_detect01/hand_dataset\\E_1721721980.npy',
 'C://ai_project01/hand_detect01/hand_dataset\\F_1721722032.npy',
 'C://ai_project01/hand_detect01/hand_dataset\\G_1721892384.npy',
 'C://ai_project01/hand_detect01/hand_dataset\\H_1721722145.npy',
 'C://ai_project01/hand_detect01/hand_dataset\\I_1721722203.npy',
 'C://ai_project01/hand_detect01/hand_dataset\\J_1721722662.npy',
 'C://ai_project01/hand_detect01/hand_dataset\\K_1721722553.npy',
 'C://ai_project01/hand_detect01/hand_dataset\\L_1721722607.npy',
 'C://ai_project01/hand_detect01/hand_dataset\\M_1721722714.npy',
 'C://ai_project01/hand_detect01/hand_dataset\\N_1721722769.npy',
 'C://ai_project01/hand_detect01/hand_dataset\\O_1721722822.npy',
 'C://ai_p

In [94]:
for file in file_list:
    print("file=",file)
    data = np.load(file)
    print("data.shape=",data.shape)

file= C://ai_project01/hand_detect01/hand_dataset\A_1721720557.npy
data.shape= (580, 79)
file= C://ai_project01/hand_detect01/hand_dataset\B_1721721796.npy
data.shape= (583, 79)
file= C://ai_project01/hand_detect01/hand_dataset\C_1721721850.npy
data.shape= (594, 79)
file= C://ai_project01/hand_detect01/hand_dataset\D_1721881189.npy
data.shape= (605, 79)
file= C://ai_project01/hand_detect01/hand_dataset\E_1721721980.npy
data.shape= (599, 79)
file= C://ai_project01/hand_detect01/hand_dataset\F_1721722032.npy
data.shape= (552, 79)
file= C://ai_project01/hand_detect01/hand_dataset\G_1721892384.npy
data.shape= (609, 79)
file= C://ai_project01/hand_detect01/hand_dataset\H_1721722145.npy
data.shape= (601, 79)
file= C://ai_project01/hand_detect01/hand_dataset\I_1721722203.npy
data.shape= (599, 79)
file= C://ai_project01/hand_detect01/hand_dataset\J_1721722662.npy
data.shape= (598, 79)
file= C://ai_project01/hand_detect01/hand_dataset\K_1721722553.npy
data.shape= (602, 79)
file= C://ai_project0

In [95]:
data_list = []

for file in file_list:
    print("file=",file)
    data = np.load(file)
    print("data.shape=",data[:550,:].shape)
    data_list.extend(data[:550,:])

file= C://ai_project01/hand_detect01/hand_dataset\A_1721720557.npy
data.shape= (550, 79)
file= C://ai_project01/hand_detect01/hand_dataset\B_1721721796.npy
data.shape= (550, 79)
file= C://ai_project01/hand_detect01/hand_dataset\C_1721721850.npy
data.shape= (550, 79)
file= C://ai_project01/hand_detect01/hand_dataset\D_1721881189.npy
data.shape= (550, 79)
file= C://ai_project01/hand_detect01/hand_dataset\E_1721721980.npy
data.shape= (550, 79)
file= C://ai_project01/hand_detect01/hand_dataset\F_1721722032.npy
data.shape= (550, 79)
file= C://ai_project01/hand_detect01/hand_dataset\G_1721892384.npy
data.shape= (550, 79)
file= C://ai_project01/hand_detect01/hand_dataset\H_1721722145.npy
data.shape= (550, 79)
file= C://ai_project01/hand_detect01/hand_dataset\I_1721722203.npy
data.shape= (550, 79)
file= C://ai_project01/hand_detect01/hand_dataset\J_1721722662.npy
data.shape= (550, 79)
file= C://ai_project01/hand_detect01/hand_dataset\K_1721722553.npy
data.shape= (550, 79)
file= C://ai_project0

In [96]:
len(data_list)

14300

In [97]:
all_data = np.array(data_list, dtype=np.float32)

all_data

array([[ 5.8251029e-01,  1.0253956e+00, -8.6173708e-07, ...,
         3.3217575e+01,  2.0925838e+01,  0.0000000e+00],
       [ 5.7534307e-01,  1.0095552e+00, -7.8575351e-07, ...,
         1.1092847e+02,  5.9893791e+01,  0.0000000e+00],
       [ 5.7339954e-01,  1.0484581e+00, -3.4167300e-07, ...,
         1.5763033e+02,  5.6520794e+01,  0.0000000e+00],
       ...,
       [ 1.1315342e-01,  9.5855498e-01, -1.2760033e-07, ...,
         8.4430885e+01,  4.4485428e+01,  2.5000000e+01],
       [ 8.1122410e-01,  4.6427894e-01, -2.8305939e-07, ...,
         5.7724419e+01,  6.8805458e+01,  2.5000000e+01],
       [ 1.1262655e-01,  9.6591896e-01, -2.9058540e-07, ...,
         7.7780045e+01,  4.3003353e+01,  2.5000000e+01]], dtype=float32)

In [98]:
all_data.shape

(14300, 79)

In [99]:
all_data_lstm = all_data.reshape(-1, 5, 79)
all_data_lstm.shape

(2860, 5, 79)

In [100]:
all_data_lstm

array([[[ 5.82510293e-01,  1.02539563e+00, -8.61737078e-07, ...,
          3.32175751e+01,  2.09258385e+01,  0.00000000e+00],
        [ 5.75343072e-01,  1.00955522e+00, -7.85753514e-07, ...,
          1.10928467e+02,  5.98937912e+01,  0.00000000e+00],
        [ 5.73399544e-01,  1.04845810e+00, -3.41673001e-07, ...,
          1.57630325e+02,  5.65207939e+01,  0.00000000e+00],
        [ 5.87400734e-01,  9.76374328e-01, -2.37280588e-07, ...,
          1.69108963e+02,  4.94954567e+01,  0.00000000e+00],
        [ 5.86500525e-01,  8.34044755e-01, -8.42697659e-07, ...,
          1.51759445e+02,  5.18361778e+01,  0.00000000e+00]],

       [[ 5.95661521e-01,  8.96553636e-01, -2.78831891e-07, ...,
          1.73260010e+02,  4.36615372e+01,  0.00000000e+00],
        [ 6.02810323e-01,  8.18312645e-01, -3.73792943e-07, ...,
          1.78499084e+02,  3.95861397e+01,  0.00000000e+00],
        [ 6.04199290e-01,  7.40784287e-01, -5.55783060e-07, ...,
          1.65490738e+02,  4.13934517e+01,  0.00000

In [101]:
X_data = all_data_lstm[:, :, :-1]
X_data

array([[[ 5.82510293e-01,  1.02539563e+00, -8.61737078e-07, ...,
          1.24081215e+02,  3.32175751e+01,  2.09258385e+01],
        [ 5.75343072e-01,  1.00955522e+00, -7.85753514e-07, ...,
          7.00741577e+01,  1.10928467e+02,  5.98937912e+01],
        [ 5.73399544e-01,  1.04845810e+00, -3.41673001e-07, ...,
          3.39927788e+01,  1.57630325e+02,  5.65207939e+01],
        [ 5.87400734e-01,  9.76374328e-01, -2.37280588e-07, ...,
          1.49057198e+01,  1.69108963e+02,  4.94954567e+01],
        [ 5.86500525e-01,  8.34044755e-01, -8.42697659e-07, ...,
          3.47784386e+01,  1.51759445e+02,  5.18361778e+01]],

       [[ 5.95661521e-01,  8.96553636e-01, -2.78831891e-07, ...,
          1.89718742e+01,  1.73260010e+02,  4.36615372e+01],
        [ 6.02810323e-01,  8.18312645e-01, -3.73792943e-07, ...,
          2.12316246e+01,  1.78499084e+02,  3.95861397e+01],
        [ 6.04199290e-01,  7.40784287e-01, -5.55783060e-07, ...,
          2.93383961e+01,  1.65490738e+02,  4.13934

In [102]:
labels = all_data_lstm[:, 0, -1]

labels

array([ 0.,  0.,  0., ..., 25., 25., 25.], dtype=float32)

In [103]:
y_data = to_categorical(labels, num_classes=len(gesture))

y_data

array([[1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.]], dtype=float32)

In [104]:
X_train, X_test, y_train, y_test = train_test_split(X_data, y_data, test_size=0.1)

In [105]:
X_train

array([[[ 7.17610776e-01,  5.30811191e-01, -3.01257131e-07, ...,
          3.81301880e+01,  1.29882641e+01,  1.07374563e+01],
        [ 7.06448376e-01,  5.10538936e-01, -5.43982459e-08, ...,
          4.17254219e+01,  1.44219036e+01,  1.08257999e+01],
        [ 7.19480157e-01,  5.25487900e-01, -2.98453386e-07, ...,
          3.74850235e+01,  1.53364391e+01,  1.10359421e+01],
        [ 7.36391246e-01,  5.18853366e-01, -2.78661389e-07, ...,
          3.70390205e+01,  1.60216560e+01,  1.22599115e+01],
        [ 7.33181238e-01,  5.14711142e-01, -2.44259979e-07, ...,
          3.62402267e+01,  1.55824585e+01,  1.25941477e+01]],

       [[ 5.21600127e-01,  6.97019339e-01,  3.89488150e-07, ...,
          5.95251656e+00,  6.74322665e-01,  7.29681492e-01],
        [ 5.25764048e-01,  6.99186146e-01,  3.91394906e-07, ...,
          5.41154766e+00,  5.24165392e-01,  7.39613056e-01],
        [ 5.32536209e-01,  7.00949311e-01,  3.80380726e-07, ...,
          6.00872231e+00,  1.02623177e+00,  6.33910

In [106]:
y_train[0:5]

array([[0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)

In [107]:
model = Sequential()

In [108]:
model.add(LSTM(256, input_shape=(5,78)))

In [109]:
model.add(Flatten())

In [110]:
model.add(Dense(128, activation='relu'))

In [111]:
model.add(Dropout(0.5) )

In [112]:
model.add(Dense(64, activation='relu'))

In [113]:
model.add(Dropout(0.5))

In [114]:
model.add(Dense(32, activation='relu'))

In [115]:
model.add(Dropout(0.5))

In [116]:
model.add(Dense(len(gesture), activation="softmax"))

In [121]:
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['acc'])

In [122]:
cb_checkpoint = ModelCheckpoint(filepath="c://ai_project01/hand_lstm_train_result/",
                                monitor="val_acc",
                                save_best_only=True
                               )

In [123]:
earlystopping = EarlyStopping(monitor="val_loss",
                              patience=500,
                             )

In [124]:
model.fit(
    X_train,
    y_train,
    validation_data=(X_test, y_test),
    epochs=1000,
    callbacks=[cb_checkpoint, earlystopping]
)

Epoch 1/1000
80/81 [============================>.] - ETA: 0s - loss: 0.3468 - acc: 0.8988

INFO:tensorflow:Assets written to: c://ai_project01/hand_lstm_train_result\/assets


INFO:tensorflow:Assets written to: c://ai_project01/hand_lstm_train_result\/assets


81/81 [==============================] - 4s 42ms/step - loss: 0.3473 - acc: 0.8986 - val_loss: 0.2375 - val_acc: 0.9406
Epoch 2/1000
78/81 [===========================>..] - ETA: 0s - loss: 0.3052 - acc: 0.9071

INFO:tensorflow:Assets written to: c://ai_project01/hand_lstm_train_result\/assets


INFO:tensorflow:Assets written to: c://ai_project01/hand_lstm_train_result\/assets


81/81 [==============================] - 3s 34ms/step - loss: 0.3039 - acc: 0.9064 - val_loss: 0.2415 - val_acc: 0.9545
Epoch 3/1000
81/81 [==============================] - 1s 9ms/step - loss: 0.3168 - acc: 0.9048 - val_loss: 0.2084 - val_acc: 0.9545
Epoch 4/1000
79/81 [============================>.] - ETA: 0s - loss: 0.3112 - acc: 0.9106

INFO:tensorflow:Assets written to: c://ai_project01/hand_lstm_train_result\/assets


INFO:tensorflow:Assets written to: c://ai_project01/hand_lstm_train_result\/assets


81/81 [==============================] - 3s 33ms/step - loss: 0.3141 - acc: 0.9099 - val_loss: 0.1974 - val_acc: 0.9685
Epoch 5/1000
81/81 [==============================] - 1s 9ms/step - loss: 0.2657 - acc: 0.9196 - val_loss: 0.1625 - val_acc: 0.9615
Epoch 6/1000
81/81 [==============================] - 1s 6ms/step - loss: 0.3142 - acc: 0.9064 - val_loss: 0.1872 - val_acc: 0.9615
Epoch 7/1000
81/81 [==============================] - 1s 7ms/step - loss: 0.3658 - acc: 0.8951 - val_loss: 0.3224 - val_acc: 0.9476
Epoch 8/1000
81/81 [==============================] - 1s 7ms/step - loss: 0.3129 - acc: 0.8990 - val_loss: 0.4003 - val_acc: 0.9231
Epoch 9/1000
81/81 [==============================] - 1s 7ms/step - loss: 0.3143 - acc: 0.9060 - val_loss: 0.2805 - val_acc: 0.9545
Epoch 10/1000
81/81 [==============================] - 1s 7ms/step - loss: 0.3145 - acc: 0.9103 - val_loss: 0.2010 - val_acc: 0.9685
Epoch 11/1000
81/81 [==============================] - 1s 7ms/step - loss: 0.2932 - acc

INFO:tensorflow:Assets written to: c://ai_project01/hand_lstm_train_result\/assets


INFO:tensorflow:Assets written to: c://ai_project01/hand_lstm_train_result\/assets


81/81 [==============================] - 3s 33ms/step - loss: 0.2806 - acc: 0.9149 - val_loss: 0.2427 - val_acc: 0.9720
Epoch 17/1000
81/81 [==============================] - 1s 8ms/step - loss: 0.2842 - acc: 0.9176 - val_loss: 0.2652 - val_acc: 0.9615
Epoch 18/1000
81/81 [==============================] - 1s 7ms/step - loss: 0.3420 - acc: 0.8982 - val_loss: 0.1618 - val_acc: 0.9650
Epoch 19/1000
81/81 [==============================] - 1s 7ms/step - loss: 0.3041 - acc: 0.8990 - val_loss: 0.1217 - val_acc: 0.9685
Epoch 20/1000
81/81 [==============================] - 1s 7ms/step - loss: 0.3161 - acc: 0.9075 - val_loss: 0.2588 - val_acc: 0.9476
Epoch 21/1000
81/81 [==============================] - 1s 7ms/step - loss: 0.3829 - acc: 0.8893 - val_loss: 0.1705 - val_acc: 0.9615
Epoch 22/1000
81/81 [==============================] - 1s 7ms/step - loss: 0.3018 - acc: 0.9087 - val_loss: 0.2076 - val_acc: 0.9476
Epoch 23/1000
81/81 [==============================] - 1s 7ms/step - loss: 0.2910 

INFO:tensorflow:Assets written to: c://ai_project01/hand_lstm_train_result\/assets


INFO:tensorflow:Assets written to: c://ai_project01/hand_lstm_train_result\/assets


81/81 [==============================] - 3s 38ms/step - loss: 0.3220 - acc: 0.9002 - val_loss: 0.1626 - val_acc: 0.9790
Epoch 27/1000
81/81 [==============================] - 1s 10ms/step - loss: 0.2568 - acc: 0.9184 - val_loss: 0.2320 - val_acc: 0.9720
Epoch 28/1000
81/81 [==============================] - 1s 7ms/step - loss: 0.3018 - acc: 0.9060 - val_loss: 0.1873 - val_acc: 0.9615
Epoch 29/1000
81/81 [==============================] - 1s 6ms/step - loss: 0.2852 - acc: 0.9103 - val_loss: 0.2135 - val_acc: 0.9580
Epoch 30/1000
81/81 [==============================] - 1s 6ms/step - loss: 0.2928 - acc: 0.9110 - val_loss: 0.2405 - val_acc: 0.9510
Epoch 31/1000
81/81 [==============================] - 1s 6ms/step - loss: 0.3058 - acc: 0.9118 - val_loss: 0.1848 - val_acc: 0.9545
Epoch 32/1000
81/81 [==============================] - 1s 6ms/step - loss: 0.2903 - acc: 0.9106 - val_loss: 0.2494 - val_acc: 0.9580
Epoch 33/1000
81/81 [==============================] - 1s 7ms/step - loss: 0.3860

INFO:tensorflow:Assets written to: c://ai_project01/hand_lstm_train_result\/assets


INFO:tensorflow:Assets written to: c://ai_project01/hand_lstm_train_result\/assets


81/81 [==============================] - 3s 32ms/step - loss: 0.2451 - acc: 0.9308 - val_loss: 0.1661 - val_acc: 0.9825
Epoch 820/1000
81/81 [==============================] - 1s 10ms/step - loss: 0.2050 - acc: 0.9390 - val_loss: 0.2518 - val_acc: 0.9615
Epoch 821/1000
81/81 [==============================] - 1s 7ms/step - loss: 0.2253 - acc: 0.9347 - val_loss: 0.2063 - val_acc: 0.9615
Epoch 822/1000
81/81 [==============================] - 1s 6ms/step - loss: 0.1936 - acc: 0.9476 - val_loss: 0.2101 - val_acc: 0.9650
Epoch 823/1000
81/81 [==============================] - 0s 6ms/step - loss: 0.2171 - acc: 0.9371 - val_loss: 0.1662 - val_acc: 0.9685
Epoch 824/1000
81/81 [==============================] - 1s 7ms/step - loss: 0.2172 - acc: 0.9386 - val_loss: 0.2607 - val_acc: 0.9650
Epoch 825/1000
81/81 [==============================] - 1s 6ms/step - loss: 0.2425 - acc: 0.9328 - val_loss: 0.2638 - val_acc: 0.9545
Epoch 826/1000
81/81 [==============================] - 1s 7ms/step - loss: